name: "Close stale issues"

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 90
          days-before-close: 30
          stale-issue-message: 'This issue has been automatically marked as stale due to 90 days of inactivity. It will be closed if no further activity occurs.'
          close-issue-message: 'Closing this issue due to inactivity.'
          stale-pr-message: ''
          close-pr-message: ''
          only-issue-labels: ''
          exempt-issue-labels: 'pinned,security'
          remove-stale-when-updated: true